customer_segmentation_purchase_behavior

In [1]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.1.1)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Loading Dataset

In [3]:
df = pd.read_excel("C:/Users/hp/OneDrive/Desktop/Project github/customer_segmentation_purchase_behavior.xlsx")

In [4]:
df.head(10)

,Customer_ID,Age,Gender,City,Income,Occupation,Marital_Status,Purchase_Date,Product_Category,Product_Name,Purchase_Amount,Quantity,Payment_Method,Discount_Applied,Loyalty_Points,Frequency_of_Purchase,Last_Purchase_Days_Ago,Customer_Lifetime_Value
0,C0,65,Other,Chennai,270245,Student,Married,2023-12-23,Fashion,Product_B,49023.52,9,Card,0.16,9018,92,159,4229255.33
1,C1,22,Male,Delhi,117681,Business,Married,2022-11-08,Groceries,Product_B,9564.26,10,Card,0.14,7625,21,99,325251.39
2,C2,26,Male,Mumbai,120619,Manager,Single,2023-01-08,Groceries,Product_A,22086.98,7,Wallet,0.43,5764,24,21,1019902.82
3,C3,50,Female,Mumbai,96061,Student,Single,2022-03-28,Furniture,Product_B,37940.85,9,Card,0.29,7078,41,56,878879.39
4,C4,70,Other,Chennai,60562,Manager,Married,2023-09-25,Groceries,Product_D,39803.27,5,Cash,0.49,282,23,43,696963.39
5,C5,20,Female,Mumbai,90993,Doctor,Married,2022-02-17,Electronics,Product_D,34431.92,4,Wallet,0.18,5993,36,226,1892590.01
6,C6,57,Female,Chennai,117802,Business,Single,2021-09-05,Groceries,Product_D,36886.25,9,Card,0.31,6929,90,315,3686446.71
7,C7,47,Male,Delhi,57408,Manager,Married,2023-09-24,Electronics,Product_B,38156.43,5,Wallet,0.33,9236,16,5,577070.52
8,C8,36,Other,Delhi,110274,Engineer,Single,2021-08-15,Groceries,Product_C,8101.77,8,Card,0.30,1339,96,287,1225432.42
9,C9,67,Female,Bangalore,121097,Business,Single,2024-07-22,Groceries,Product_A,10434.23,10,Cash,0.17,3495,32,25,440680.27

In [5]:
df.tail()

,Customer_ID,Age,Gender,City,Income,Occupation,Marital_Status,Purchase_Date,Product_Category,Product_Name,Purchase_Amount,Quantity,Payment_Method,Discount_Applied,Loyalty_Points,Frequency_of_Purchase,Last_Purchase_Days_Ago,Customer_Lifetime_Value
89995,C89995,48,Other,Bangalore,120583,Student,Single,2022-11-20,Groceries,Product_B,44275.89,9,Wallet,0.06,8021,92,1,3350094.50
89996,C89996,45,Male,Mumbai,167233,Doctor,Married,2025-02-05,Groceries,Product_A,30342.00,3,Cash,0.39,9367,69,239,3653739.78
89997,C89997,56,Other,Delhi,224624,Manager,Single,2021-01-09,Furniture,Product_B,21777.15,4,Wallet,0.26,5428,33,185,1078522.32
89998,C89998,21,Male,Chennai,289217,Business,Married,2022-11-22,Groceries,Product_A,45405.81,10,Cash,0.09,3373,74,147,2072232.77
89999,C89999,48,Female,Chennai,197956,Manager,Married,2022-04-08,Furniture,Product_D,11979.78,3,UPI,0.01,6259,1,115,21202.18

In [6]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Income', 'Occupation',
       'Marital_Status', 'Purchase_Date', 'Product_Category', 'Product_Name',
       'Purchase_Amount', 'Quantity', 'Payment_Method', 'Discount_Applied',
       'Loyalty_Points', 'Frequency_of_Purchase', 'Last_Purchase_Days_Ago',
       'Customer_Lifetime_Value'],
      dtype='object')

In [7]:
df.shape

(90000, 18)

Data Cleaning

In [8]:
df.drop_duplicates()

,Customer_ID,Age,Gender,City,Income,Occupation,Marital_Status,Purchase_Date,Product_Category,Product_Name,Purchase_Amount,Quantity,Payment_Method,Discount_Applied,Loyalty_Points,Frequency_of_Purchase,Last_Purchase_Days_Ago,Customer_Lifetime_Value
0,C0,65,Other,Chennai,270245,Student,Married,2023-12-23,Fashion,Product_B,49023.52,9,Card,0.16,9018,92,159,4229255.33
1,C1,22,Male,Delhi,117681,Business,Married,2022-11-08,Groceries,Product_B,9564.26,10,Card,0.14,7625,21,99,325251.39
2,C2,26,Male,Mumbai,120619,Manager,Single,2023-01-08,Groceries,Product_A,22086.98,7,Wallet,0.43,5764,24,21,1019902.82
3,C3,50,Female,Mumbai,96061,Student,Single,2022-03-28,Furniture,Product_B,37940.85,9,Card,0.29,7078,41,56,878879.39
4,C4,70,Other,Chennai,60562,Manager,Married,2023-09-25,Groceries,Product_D,39803.27,5,Cash,0.49,282,23,43,696963.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,C89995,48,Other,Bangalore,120583,Student,Single,2022-11-20,Groceries,Product_B,44275.89,9,Wallet,0.06,8021,92,1,3350094.50
89996,C89996,45,Male,Mumbai,167233,Doctor,Married,2025-02-05,Groceries,Product_A,30342.00,3,Cash,0.39,9367,69,239,3653739.78
89997,C89997,56,Other,Delhi,224624,Manager,Single,2021-01-09,Furniture,Product_B,21777.15,4,Wallet,0.26,5428,33,185,1078522.32
89998,C89998,21,Male,Chennai,289217,Business,Married,2022-11-22,Groceries,Product_A,45405.81,10,Cash,0.09,3373,74,147,2072232.77
89999,C89999,48,Female,Chennai,197956,Manager,Married,2022-04-08,Furniture,Product_D,11979.78,3,UPI,0.01,6259,1,115,21202.18

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer_ID              90000 non-null  object
 1   Age                      90000 non-null  int64
 2   Gender                   90000 non-null  object
 3   City                     90000 non-null  object
 4   Income                   90000 non-null  int64
 5   Occupation               90000 non-null  object
 6   Marital_Status           90000 non-null  object
 7   Purchase_Date            90000 non-null  object
 8   Product_Category         90000 non-null  object
 9   Product_Name             90000 non-null  object
 10  Purchase_Amount          90000 non-null  float64
 11  Quantity                 90000 non-null  int64
 12  Payment_Method           90000 non-null  object
 13  Discount_Applied         90000 non-null  float64
 14  Loyalty_Points           90000 non-null  int64
 15  Frequency_of_Purchase    90000 non-null  int64
 16  Last_Purchase_Days_Ago   90000 non-null  int64
 17  Customer_Lifetime_Value  90000 non-null  float64
dtypes: float64(3), int64(6), object(9)
memory usage: 12.4+ MB

In [10]:
df.isnull().sum()

Customer_ID                0
Age                        0
Gender                     0
City                       0
Income                     0
Occupation                 0
Marital_Status             0
Purchase_Date              0
Product_Category           0
Product_Name               0
Purchase_Amount            0
Quantity                   0
Payment_Method             0
Discount_Applied           0
Loyalty_Points             0
Frequency_of_Purchase      0
Last_Purchase_Days_Ago     0
Customer_Lifetime_Value    0
dtype: int64

In [11]:
df.describe()

,Age,Income,Purchase_Amount,Quantity,Discount_Applied,Loyalty_Points,Frequency_of_Purchase,Last_Purchase_Days_Ago,Customer_Lifetime_Value
count,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,90000.000000,9.000000e+04
mean,43.930178,159492.967967,25073.874292,5.485878,0.249917,5010.518711,50.456722,183.580689,1.576689e+06
std,15.295001,80805.498430,14366.053169,2.873152,0.144385,2886.250838,28.826836,105.352137,1.558029e+06
min,18.000000,20005.000000,100.780000,1.000000,0.000000,0.000000,1.000000,1.000000,1.545500e+02
25%,31.000000,89248.750000,12646.375000,3.000000,0.120000,2509.000000,26.000000,93.000000,3.921952e+05
50%,44.000000,159644.500000,25143.090000,5.000000,0.250000,5027.000000,50.000000,184.000000,1.074800e+06
75%,57.000000,229818.500000,37508.295000,8.000000,0.370000,7511.000000,75.000000,275.000000,2.270137e+06
max,70.000000,299990.000000,49999.930000,10.000000,0.500000,10000.000000,100.000000,365.000000,9.856954e+06

Visualization Dashboards

In [17]:
import plotly.express as px

In [12]:
total_revenue = df['Purchase_Amount'].sum()
total_customers = df['Customer_ID'].nunique()
avg_clv = df['Customer_Lifetime_Value'].mean()

In [13]:
category_sales = df.groupby('Product_Category')['Purchase_Amount'].sum()

In [14]:
gender_sales = df.groupby('Gender')['Purchase_Amount'].sum()

In [15]:
city_sales = df.groupby('City')['Purchase_Amount'].sum()

Income vs Purchase Amount

In [18]:
px.scatter(df,
           x='Income',
           y='Purchase_Amount',
           color='Gender')

Customer Lifetime Value Analysis

In [19]:
px.histogram(df,
             x='Customer_Lifetime_Value')

Purchase Frequency Analysis

In [20]:
payment = df['Payment_Method'].value_counts()

Monthly Sales Trend

In [21]:
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

Dashboard

In [23]:
import pandas as pd
from dash import Dash, dcc, html
import plotly.express as px

In [24]:
# Load Data
df = pd.read_excel("C:/Users/hp/OneDrive/Desktop/Project github/customer_segmentation_purchase_behavior.xlsx")

In [25]:
# Convert Date
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'])

In [26]:
# KPIs
total_revenue = df['Purchase_Amount'].sum()
total_customers = df['Customer_ID'].nunique()
avg_purchase = df['Purchase_Amount'].mean()
avg_clv = df['Customer_Lifetime_Value'].mean()

In [27]:
# Charts

# Category Sales
category_sales = df.groupby(
    'Product_Category'
)['Purchase_Amount'].sum().reset_index()

fig_category = px.bar(
    category_sales,
    x='Product_Category',
    y='Purchase_Amount',
    title='Revenue by Product Category'
)

In [28]:
# Gender Analysis
gender_sales = df.groupby(
    'Gender'
)['Purchase_Amount'].sum().reset_index()

fig_gender = px.pie(
    gender_sales,
    names='Gender',
    values='Purchase_Amount',
    hole=0.4,
    title='Gender-wise Purchases'
)

In [29]:
# City Sales
city_sales = df.groupby(
    'City'
)['Purchase_Amount'].sum().reset_index()

fig_city = px.bar(
    city_sales,
    x='Purchase_Amount',
    y='City',
    orientation='h',
    title='City-wise Revenue'
)

In [30]:
# Income vs Purchase
fig_income = px.scatter(
    df,
    x='Income',
    y='Purchase_Amount',
    color='Gender',
    title='Income vs Purchase Amount'
)

In [31]:
# CLV Distribution
fig_clv = px.histogram(
    df,
    x='Customer_Lifetime_Value',
    nbins=30,
    title='Customer Lifetime Value Distribution'
)

In [32]:
# Monthly Sales
monthly_sales = df.groupby(
    df['Purchase_Date'].dt.month_name()
)['Purchase_Amount'].sum().reset_index()

fig_monthly = px.line(
    monthly_sales,
    x='Purchase_Date',
    y='Purchase_Amount',
    markers=True,
    title='Monthly Sales Trend'
)

In [36]:
import webbrowser

webbrowser.open('index.html')

True

In [39]:
# CLV Distribution
fig_clv = px.histogram(
    df,
    x='Customer_Lifetime_Value',
    nbins=30,
    title='Customer Lifetime Value Distribution'
)

In [40]:
# Monthly Sales Trend
monthly_sales = df.groupby(
    df['Purchase_Date'].dt.month_name()
)['Purchase_Amount'].sum().reset_index()

monthly_sales.columns = ['Month', 'Revenue']

fig_monthly = px.line(
    monthly_sales,
    x='Month',
    y='Revenue',
    markers=True,
    title='Monthly Revenue Trend'
)

In [41]:
# Loyalty Points
fig_loyalty = px.box(
    df,
    y='Loyalty_Points',
    title='Loyalty Points Distribution'
)