food_delivery_analysis

In [65]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.1.1)

In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Loading Data set

In [67]:
df = pd.read_excel("C:/Users/hp/OneDrive/Desktop/Project github/food_delivery_analysis_data.xlsx")

Data Cleaning

In [68]:
df.head(10)

,Order_ID,Customer_ID,Restaurant_ID,City,Order_Date,Delivery_Time_Minutes,Order_Value,Delivery_Fee,Discount,Payment_Method,Order_Status,Rating,Delivery_Partner_ID,Distance_km,Prep_Time_Minutes,Cuisine_Type,Is_Peak_Hour,Weather,Traffic_Level
0,O0,777900,5401,Chennai,2023-09-14,13,992.04,59.14,303.81,Card,Cancelled,3,1894,9.95,35,Desserts,0,Foggy,Medium
1,O1,80192,7584,Kolkata,2023-11-10,26,306.66,18.60,482.44,UPI,Cancelled,2,8928,4.91,34,Italian,0,Foggy,Low
2,O2,833783,4345,Delhi,2022-09-26,87,1876.82,37.36,308.53,Wallet,Delivered,1,6689,4.78,16,Desserts,0,Clear,Medium
3,O3,769494,4710,Kolkata,2023-02-28,46,394.26,21.61,307.48,Cash,Delivered,3,7934,19.65,48,Italian,1,Rainy,Medium
4,O4,3185,7449,Bhopal,2022-05-08,72,1579.75,44.84,366.02,Cash,Cancelled,4,9735,16.78,45,Indian,1,Foggy,Medium
5,O5,537378,3069,Chennai,2023-07-01,81,1446.33,10.10,2.77,Cash,Delivered,3,7604,12.85,26,Desserts,0,Rainy,High
6,O6,607733,3260,Bhopal,2023-07-11,33,1565.21,13.50,59.82,Wallet,Cancelled,5,3382,18.50,60,Chinese,1,Foggy,Medium
7,O7,65056,2390,Delhi,2022-02-08,15,1335.06,89.32,458.67,Cash,Pending,5,2480,17.19,46,Chinese,1,Clear,Low
8,O8,967284,8104,Chennai,2022-12-24,44,1666.31,80.76,80.27,Wallet,Delivered,4,9813,15.47,16,Fast Food,1,Clear,Low
9,O9,581699,5753,Bhopal,2022-01-14,66,634.45,88.82,429.34,Cash,Pending,3,2757,17.36,14,Desserts,0,Rainy,Low

In [69]:
df.tail()

,Order_ID,Customer_ID,Restaurant_ID,City,Order_Date,Delivery_Time_Minutes,Order_Value,Delivery_Fee,Discount,Payment_Method,Order_Status,Rating,Delivery_Partner_ID,Distance_km,Prep_Time_Minutes,Cuisine_Type,Is_Peak_Hour,Weather,Traffic_Level
59995,O59995,963804,9470,Bhopal,2023-01-02,26,1444.12,65.94,442.69,Wallet,Delivered,2,8609,8.78,15,Indian,0,Foggy,Low
59996,O59996,704113,4071,Delhi,2024-01-28,87,1369.46,58.18,29.62,Cash,Cancelled,5,9558,3.99,23,Indian,0,Foggy,Medium
59997,O59997,695508,6824,Kolkata,2023-09-28,56,1736.91,73.40,57.58,Card,Cancelled,5,7822,4.61,49,Italian,0,Clear,High
59998,O59998,456034,541,Bhopal,2023-09-28,31,1607.03,55.82,95.13,Card,Delivered,3,9594,1.18,7,Indian,0,Foggy,Medium
59999,O59999,186270,7333,Kolkata,2024-01-04,90,1021.56,86.23,318.51,Wallet,Pending,2,3850,7.13,15,Desserts,1,Foggy,High

In [70]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Restaurant_ID', 'City', 'Order_Date',
       'Delivery_Time_Minutes', 'Order_Value', 'Delivery_Fee', 'Discount',
       'Payment_Method', 'Order_Status', 'Rating', 'Delivery_Partner_ID',
       'Distance_km', 'Prep_Time_Minutes', 'Cuisine_Type', 'Is_Peak_Hour',
       'Weather', 'Traffic_Level'],
      dtype='object')

In [71]:
df.shape

(60000, 19)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               60000 non-null  object
 1   Customer_ID            60000 non-null  int64
 2   Restaurant_ID          60000 non-null  int64
 3   City                   60000 non-null  object
 4   Order_Date             60000 non-null  object
 5   Delivery_Time_Minutes  60000 non-null  int64
 6   Order_Value            60000 non-null  float64
 7   Delivery_Fee           60000 non-null  float64
 8   Discount               60000 non-null  float64
 9   Payment_Method         60000 non-null  object
 10  Order_Status           60000 non-null  object
 11  Rating                 60000 non-null  int64
 12  Delivery_Partner_ID    60000 non-null  int64
 13  Distance_km            60000 non-null  float64
 14  Prep_Time_Minutes      60000 non-null  int64
 15  Cuisine_Type           60000 non-null  object
 16  Is_Peak_Hour           60000 non-null  int64
 17  Weather                60000 non-null  object
 18  Traffic_Level          60000 non-null  object
dtypes: float64(4), int64(7), object(8)
memory usage: 8.7+ MB

In [73]:
df.isnull().sum()

Order_ID                 0
Customer_ID              0
Restaurant_ID            0
City                     0
Order_Date               0
Delivery_Time_Minutes    0
Order_Value              0
Delivery_Fee             0
Discount                 0
Payment_Method           0
Order_Status             0
Rating                   0
Delivery_Partner_ID      0
Distance_km              0
Prep_Time_Minutes        0
Cuisine_Type             0
Is_Peak_Hour             0
Weather                  0
Traffic_Level            0
dtype: int64

In [74]:
df.drop_duplicates()

,Order_ID,Customer_ID,Restaurant_ID,City,Order_Date,Delivery_Time_Minutes,Order_Value,Delivery_Fee,Discount,Payment_Method,Order_Status,Rating,Delivery_Partner_ID,Distance_km,Prep_Time_Minutes,Cuisine_Type,Is_Peak_Hour,Weather,Traffic_Level
0,O0,777900,5401,Chennai,2023-09-14,13,992.04,59.14,303.81,Card,Cancelled,3,1894,9.95,35,Desserts,0,Foggy,Medium
1,O1,80192,7584,Kolkata,2023-11-10,26,306.66,18.60,482.44,UPI,Cancelled,2,8928,4.91,34,Italian,0,Foggy,Low
2,O2,833783,4345,Delhi,2022-09-26,87,1876.82,37.36,308.53,Wallet,Delivered,1,6689,4.78,16,Desserts,0,Clear,Medium
3,O3,769494,4710,Kolkata,2023-02-28,46,394.26,21.61,307.48,Cash,Delivered,3,7934,19.65,48,Italian,1,Rainy,Medium
4,O4,3185,7449,Bhopal,2022-05-08,72,1579.75,44.84,366.02,Cash,Cancelled,4,9735,16.78,45,Indian,1,Foggy,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,O59995,963804,9470,Bhopal,2023-01-02,26,1444.12,65.94,442.69,Wallet,Delivered,2,8609,8.78,15,Indian,0,Foggy,Low
59996,O59996,704113,4071,Delhi,2024-01-28,87,1369.46,58.18,29.62,Cash,Cancelled,5,9558,3.99,23,Indian,0,Foggy,Medium
59997,O59997,695508,6824,Kolkata,2023-09-28,56,1736.91,73.40,57.58,Card,Cancelled,5,7822,4.61,49,Italian,0,Clear,High
59998,O59998,456034,541,Bhopal,2023-09-28,31,1607.03,55.82,95.13,Card,Delivered,3,9594,1.18,7,Indian,0,Foggy,Medium
59999,O59999,186270,7333,Kolkata,2024-01-04,90,1021.56,86.23,318.51,Wallet,Pending,2,3850,7.13,15,Desserts,1,Foggy,High

Exploratory Data Analysis

In [75]:
df.describe()

,Customer_ID,Restaurant_ID,Delivery_Time_Minutes,Order_Value,Delivery_Fee,Discount,Rating,Delivery_Partner_ID,Distance_km,Prep_Time_Minutes,Is_Peak_Hour
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,497166.573567,5048.232333,50.009500,1050.651548,54.984212,250.128537,2.989017,5486.272583,10.514790,32.524417,0.500783
std,288596.223355,2849.802836,23.424207,547.369614,26.005486,144.270501,1.414318,2603.955587,5.486631,16.178049,0.500004
min,1005.000000,100.000000,10.000000,100.000000,10.000000,0.010000,1.000000,1000.000000,1.000000,5.000000,0.000000
25%,246761.750000,2597.000000,30.000000,575.940000,32.390000,125.180000,2.000000,3227.000000,5.730000,18.000000,0.000000
50%,496282.000000,5040.000000,50.000000,1049.895000,54.960000,250.190000,3.000000,5479.000000,10.540000,33.000000,1.000000
75%,746843.000000,7499.250000,70.000000,1523.927500,77.560000,375.042500,4.000000,7735.000000,15.270000,47.000000,1.000000
max,999950.000000,9999.000000,90.000000,2000.000000,100.000000,500.000000,5.000000,9999.000000,20.000000,60.000000,1.000000

VISUALIZATION DASHBOARD

In [76]:
import plotly.express as px

In [77]:
total_orders = df['Order_ID'].nunique()
total_revenue = df['Order_Value'].sum()
avg_delivery = df['Delivery_Time_Minutes'].mean()
avg_rating = df['Rating'].mean()

Revenue by City

In [78]:
city_sales = df.groupby('City')['Order_Value'].sum().reset_index()

fig = px.bar(
    city_sales,
    x='City',
    y='Order_Value',
    color='City',
    title='Revenue by City'
)

In [79]:
daily_orders = df.groupby('Order_Date')['Order_ID'].count().reset_index()

fig = px.line(
    daily_orders,
    x='Order_Date',
    y='Order_ID',
    title='Daily Orders Trend'
)

In [80]:
cuisine = df.groupby('Cuisine_Type')['Order_ID'].count().reset_index()

fig = px.pie(
    cuisine,
    names='Cuisine_Type',
    values='Order_ID',
    hole=0.5
)

In [81]:
fig = px.scatter(
    df,
    x='Distance_km',
    y='Delivery_Time_Minutes',
    color='Traffic_Level',
    size='Order_Value'
)

In [82]:
fig = px.box(
    df,
    x='Weather',
    y='Delivery_Time_Minutes',
    color='Weather'
)

In [83]:
fig = px.density_heatmap(
    df,
    x='Traffic_Level',
    y='Delivery_Time_Minutes'
)

In [84]:
fig = px.pie(
    df,
    names='Payment_Method',
    title='Payment Methods'
)

In [93]:
fig = px.bar(
    df,
    x='Is_Peak_Hour',
    y='Order_Value',
    color='Order_Status'
)

In [86]:
fig = px.histogram(
    df,
    x='Rating',
    nbins=10
)

In [91]:
fig = px.treemap(
    df,
    path=['City', 'Restaurant_ID'],
    values='Order_Value'
)