HR Analytics Data

In [2]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in .\.venv\Lib\site-packages (26.1.1)

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

Loading Dataset

In [19]:
df = pd.read_csv("C:/Users/hp/OneDrive/Desktop/Project github/hr_analytics_data.csv")

Exploratory Data Analysis

In [5]:
df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Experience_Years,Education_Level,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Joining_Date,Last_Promotion_Date,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
0,E0,57,Male,Operations,Consultant,7.8,Bachelor,137844,2,33,1,1,2012-06-22,2020-03-20,186,19,15,5
1,E1,42,Male,Finance,Manager,24.5,PhD,150548,1,43,0,1,2012-06-11,2023-09-06,101,12,13,3
2,E2,46,Other,Sales,Manager,9.5,Master,24715,3,55,0,0,2019-08-03,2021-11-15,96,5,6,2
3,E3,38,Male,Sales,Engineer,3.4,PhD,178740,4,46,0,1,2020-04-20,2016-07-17,17,17,5,3
4,E4,27,Other,Marketing,Analyst,35.1,Master,67125,3,44,1,1,2015-09-01,2013-11-08,16,18,6,1

In [6]:
df.tail()

,Employee_ID,Age,Gender,Department,Job_Role,Experience_Years,Education_Level,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Joining_Date,Last_Promotion_Date,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
99995,E99995,36,Other,IT,Engineer,36.5,Master,94820,4,51,1,1,2013-06-06,2014-09-23,163,10,2,1
99996,E99996,41,Male,Marketing,Engineer,22.2,PhD,60649,4,58,1,0,2014-05-02,2016-07-27,93,6,13,2
99997,E99997,52,Female,Marketing,Consultant,0.9,Master,177262,3,57,0,1,2014-03-13,2017-05-27,58,8,6,5
99998,E99998,38,Other,Operations,Consultant,26.4,Bachelor,150627,1,43,1,1,2013-05-13,2015-10-09,172,17,1,2
99999,E99999,51,Other,HR,Consultant,37.4,PhD,110088,5,31,1,1,2010-04-21,2017-07-31,99,14,14,1

In [7]:
df.describe()

,Age,Experience_Years,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000
mean,40.004410,19.930574,109935.401400,3.000980,44.980410,0.499160,0.500900,100.054440,9.987530,8.017770,3.00957
std,11.842247,11.537606,51936.893678,1.418231,8.948535,0.500002,0.500002,58.103969,6.052884,4.308536,1.41475
min,20.000000,0.000000,20002.000000,1.000000,30.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.00000
25%,30.000000,9.900000,64910.000000,2.000000,37.000000,0.000000,0.000000,50.000000,5.000000,4.000000,2.00000
50%,40.000000,19.900000,110064.000000,3.000000,45.000000,0.000000,1.000000,100.000000,10.000000,8.000000,3.00000
75%,50.000000,29.900000,154972.500000,4.000000,53.000000,1.000000,1.000000,151.000000,15.000000,12.000000,4.00000
max,60.000000,40.000000,199997.000000,5.000000,60.000000,1.000000,1.000000,200.000000,20.000000,15.000000,5.00000

In [8]:
df.shape

(100000, 18)

In [9]:
df.nunique()

Employee_ID            100000
Age                        41
Gender                      3
Department                  6
Job_Role                    5
Experience_Years          401
Education_Level             4
Salary                  76554
Performance_Rating          5
Work_Hours_Per_Week        31
Overtime                    2
Attrition                   2
Joining_Date             4001
Last_Promotion_Date      4001
Training_Hours            201
Sick_Leaves                21
Projects_Handled           15
Manager_Rating              5
dtype: int64

In [10]:
df.columns

Index(['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role',
       'Experience_Years', 'Education_Level', 'Salary', 'Performance_Rating',
       'Work_Hours_Per_Week', 'Overtime', 'Attrition', 'Joining_Date',
       'Last_Promotion_Date', 'Training_Hours', 'Sick_Leaves',
       'Projects_Handled', 'Manager_Rating'],
      dtype='str')

Data Cleaning

In [11]:
df.isnull()

,Employee_ID,Age,Gender,Department,Job_Role,Experience_Years,Education_Level,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Joining_Date,Last_Promotion_Date,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.dropna()

,Employee_ID,Age,Gender,Department,Job_Role,Experience_Years,Education_Level,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Joining_Date,Last_Promotion_Date,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
0,E0,57,Male,Operations,Consultant,7.8,Bachelor,137844,2,33,1,1,2012-06-22,2020-03-20,186,19,15,5
1,E1,42,Male,Finance,Manager,24.5,PhD,150548,1,43,0,1,2012-06-11,2023-09-06,101,12,13,3
2,E2,46,Other,Sales,Manager,9.5,Master,24715,3,55,0,0,2019-08-03,2021-11-15,96,5,6,2
3,E3,38,Male,Sales,Engineer,3.4,PhD,178740,4,46,0,1,2020-04-20,2016-07-17,17,17,5,3
4,E4,27,Other,Marketing,Analyst,35.1,Master,67125,3,44,1,1,2015-09-01,2013-11-08,16,18,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,E99995,36,Other,IT,Engineer,36.5,Master,94820,4,51,1,1,2013-06-06,2014-09-23,163,10,2,1
99996,E99996,41,Male,Marketing,Engineer,22.2,PhD,60649,4,58,1,0,2014-05-02,2016-07-27,93,6,13,2
99997,E99997,52,Female,Marketing,Consultant,0.9,Master,177262,3,57,0,1,2014-03-13,2017-05-27,58,8,6,5
99998,E99998,38,Other,Operations,Consultant,26.4,Bachelor,150627,1,43,1,1,2013-05-13,2015-10-09,172,17,1,2
99999,E99999,51,Other,HR,Consultant,37.4,PhD,110088,5,31,1,1,2010-04-21,2017-07-31,99,14,14,1

In [13]:
df.drop_duplicates()

,Employee_ID,Age,Gender,Department,Job_Role,Experience_Years,Education_Level,Salary,Performance_Rating,Work_Hours_Per_Week,Overtime,Attrition,Joining_Date,Last_Promotion_Date,Training_Hours,Sick_Leaves,Projects_Handled,Manager_Rating
0,E0,57,Male,Operations,Consultant,7.8,Bachelor,137844,2,33,1,1,2012-06-22,2020-03-20,186,19,15,5
1,E1,42,Male,Finance,Manager,24.5,PhD,150548,1,43,0,1,2012-06-11,2023-09-06,101,12,13,3
2,E2,46,Other,Sales,Manager,9.5,Master,24715,3,55,0,0,2019-08-03,2021-11-15,96,5,6,2
3,E3,38,Male,Sales,Engineer,3.4,PhD,178740,4,46,0,1,2020-04-20,2016-07-17,17,17,5,3
4,E4,27,Other,Marketing,Analyst,35.1,Master,67125,3,44,1,1,2015-09-01,2013-11-08,16,18,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,E99995,36,Other,IT,Engineer,36.5,Master,94820,4,51,1,1,2013-06-06,2014-09-23,163,10,2,1
99996,E99996,41,Male,Marketing,Engineer,22.2,PhD,60649,4,58,1,0,2014-05-02,2016-07-27,93,6,13,2
99997,E99997,52,Female,Marketing,Consultant,0.9,Master,177262,3,57,0,1,2014-03-13,2017-05-27,58,8,6,5
99998,E99998,38,Other,Operations,Consultant,26.4,Bachelor,150627,1,43,1,1,2013-05-13,2015-10-09,172,17,1,2
99999,E99999,51,Other,HR,Consultant,37.4,PhD,110088,5,31,1,1,2010-04-21,2017-07-31,99,14,14,1

Visualization Dashboards

In [18]:
import pandas as pd
import plotly.express as px

In [20]:
# Load data
df = pd.read_csv("C:/Users/hp/OneDrive/Desktop/Project github/hr_analytics_data.csv")

In [21]:
# Date columns
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df["Joining_Month"] = df["Joining_Date"].dt.to_period("M").astype(str)

In [22]:
# ==========================
# KPI (optional)
# ==========================
print("Total Employees:", df["Employee_ID"].nunique())
print("Average Salary:", round(df["Salary"].mean(), 2))
print("Attrition Rate:", round(df["Attrition"].mean() * 100, 2), "%")

Total Employees: 100000
Average Salary: 109935.4
Attrition Rate: 50.09 %

In [23]:
# ==========================
# 1. Employee count by department
# ==========================
dept = df.groupby("Department")["Employee_ID"].count().reset_index()

fig1 = px.bar(
    dept,
    x="Department",
    y="Employee_ID",
    title="Employee Count by Department"
)
fig1.show()

In [24]:
# ==========================
# 2. Attrition by department
# ==========================
attrition = df.groupby("Department")["Attrition"].mean().reset_index()

fig2 = px.bar(
    attrition,
    x="Department",
    y="Attrition",
    title="Attrition Rate by Department"
)
fig2.show()

In [25]:
# ==========================
# 3. Salary by job role
# ==========================
salary_role = df.groupby("Job_Role")["Salary"].mean().reset_index()

fig3 = px.bar(
    salary_role,
    x="Job_Role",
    y="Salary",
    title="Average Salary by Job Role"
)
fig3.show()

In [ ]:
# ==========================
# 4. Performance vs experience
# ==========================
fig4 = px.scatter(
    df,
    x="Experience_Years",
    y="Performance_Rating",
    size="Salary",
    color="Department",
    title="Performance vs Experience"
)
fig4.show()

In [26]:
# ==========================
# 5. Gender distribution
# ==========================
gender = df.groupby("Gender")["Employee_ID"].count().reset_index()

fig5 = px.pie(
    gender,
    names="Gender",
    values="Employee_ID",
    title="Gender Distribution"
)
fig5.show()

In [27]:
# ==========================
# 6. Overtime vs attrition
# ==========================
overtime = df.groupby("Overtime")["Attrition"].mean().reset_index()

fig6 = px.bar(
    overtime,
    x="Overtime",
    y="Attrition",
    title="Overtime vs Attrition"
)
fig6.show()

In [28]:
# ==========================
# 7. Training hours vs performance
# ==========================
fig7 = px.scatter(
    df,
    x="Training_Hours",
    y="Performance_Rating",
    color="Department",
    title="Training Hours vs Performance"
)
fig7.show()

In [29]:
# ==========================
# 8. Hiring trend
# ==========================
hiring = df.groupby("Joining_Month")["Employee_ID"].count().reset_index()

fig8 = px.line(
    hiring,
    x="Joining_Month",
    y="Employee_ID",
    title="Hiring Trend Over Time"
)
fig8.show()

In [31]:
# ==========================
# 9. Sick leaves by department
# ==========================
sick = df.groupby("Department")["Sick_Leaves"].mean().reset_index()

fig9 = px.bar(
    sick,
    x="Department",
    y="Sick_Leaves",
    title="Average Sick Leaves by Department"
)
fig9.show()

In [33]:
# ==========================
# 10. Manager rating by department
# ==========================
mgr = df.groupby("Department")["Manager_Rating"].mean().reset_index()

fig10 = px.bar(
    mgr,
    x="Department",
    y="Manager_Rating",
    title="Average Manager Rating by Department"
)
fig10.show()