Loan_default_risk

In [1]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.1.1)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

Loading Data set

In [3]:
df = pd.read_csv("C:/Users/hp/OneDrive/Desktop/Project github/loan_default_risk_data.csv")

Data Cleaning

In [4]:
df.head(10)

,Loan_ID,Customer_ID,Age,Gender,City,Income,Employment_Type,Credit_Score,Loan_Amount,Loan_Term_Months,Interest_Rate,EMI,Existing_Loans,Debt_to_Income,Payment_History,Loan_Purpose,Default_Flag,Application_Date
0,L0,573890,29,Male,Chennai,60745,Unemployed,722,324677,12,11.70,30222.02,5,1.00,18,Home,0,2017-09-06
1,L1,618322,22,Other,Bhopal,83424,Self-Employed,387,155281,36,15.96,5001.77,3,0.71,23,Education,1,2016-12-18
2,L2,734045,29,Other,Mumbai,113963,Unemployed,493,79923,36,17.37,2605.71,0,0.68,32,Car,0,2022-08-16
3,L3,302103,35,Male,Mumbai,53137,Unemployed,465,225259,60,7.61,4040.02,5,0.16,32,Car,0,2021-06-18
4,L4,91731,38,Male,Bhopal,38439,Salaried,789,407615,12,7.05,36362.65,4,0.32,1,Car,1,2021-04-29
5,L5,239631,54,Female,Mumbai,54966,Self-Employed,528,40349,60,15.92,779.54,0,0.11,75,Business,1,2018-05-01
6,L6,236430,56,Other,Bhopal,89186,Salaried,664,183289,60,14.41,3495.02,1,0.50,78,Business,0,2017-12-10
7,L7,43734,33,Female,Mumbai,34583,Unemployed,496,177367,24,13.79,8409.41,0,0.25,70,Education,1,2019-05-14
8,L8,999181,50,Female,Chennai,188577,Unemployed,658,430897,60,10.97,7969.44,1,0.42,26,Home,1,2016-11-15
9,L9,776928,44,Female,Kolkata,104902,Self-Employed,869,116890,12,16.78,11375.35,5,0.63,24,Home,0,2018-12-18

In [5]:
df.tail()

,Loan_ID,Customer_ID,Age,Gender,City,Income,Employment_Type,Credit_Score,Loan_Amount,Loan_Term_Months,Interest_Rate,EMI,Existing_Loans,Debt_to_Income,Payment_History,Loan_Purpose,Default_Flag,Application_Date
94995,L94995,556371,20,Other,Kolkata,134094,Self-Employed,860,102145,36,10.52,3135.85,2,0.39,45,Personal,1,2022-08-21
94996,L94996,966331,60,Female,Kolkata,167802,Self-Employed,676,430397,24,11.84,20056.50,5,0.42,94,Business,0,2016-06-30
94997,L94997,361133,57,Male,Mumbai,113700,Unemployed,653,467880,12,12.16,43731.18,0,0.85,99,Business,1,2018-05-24
94998,L94998,934984,22,Other,Bhopal,170375,Salaried,521,177517,24,14.65,8480.14,4,0.76,73,Personal,1,2019-04-05
94999,L94999,339337,34,Female,Mumbai,174125,Unemployed,616,389875,36,12.82,12218.25,5,0.46,21,Education,1,2015-05-03

In [6]:
df.columns

Index(['Loan_ID', 'Customer_ID', 'Age', 'Gender', 'City', 'Income',
       'Employment_Type', 'Credit_Score', 'Loan_Amount', 'Loan_Term_Months',
       'Interest_Rate', 'EMI', 'Existing_Loans', 'Debt_to_Income',
       'Payment_History', 'Loan_Purpose', 'Default_Flag', 'Application_Date'],
      dtype='object')

In [7]:
df.shape

(95000, 18)

Exploratory Data Analysis

In [8]:
df.describe()

,Customer_ID,Age,Income,Credit_Score,Loan_Amount,Loan_Term_Months,Interest_Rate,EMI,Existing_Loans,Debt_to_Income,Payment_History,Default_Flag
count,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000,95000.000000
mean,499969.892600,41.493621,104938.545105,599.228347,252601.801389,32.945053,11.501819,11945.478881,2.503484,0.500033,49.936905,0.498905
std,288552.784089,13.867253,54917.313222,173.416088,143127.019726,17.776559,3.760803,10613.778795,1.707512,0.288904,29.139272,0.500001
min,1009.000000,18.000000,10003.000000,300.000000,5001.000000,12.000000,5.000000,92.470000,0.000000,0.000000,0.000000,0.000000
25%,249780.250000,29.000000,57245.750000,449.000000,128373.750000,12.000000,8.250000,4330.120000,1.000000,0.250000,25.000000,0.000000
50%,499017.500000,42.000000,104968.500000,598.000000,252353.500000,24.000000,11.510000,8549.065000,3.000000,0.500000,50.000000,0.000000
75%,750693.000000,54.000000,152717.250000,749.000000,376580.000000,60.000000,14.750000,15784.355000,4.000000,0.750000,75.000000,1.000000
max,999998.000000,65.000000,200000.000000,900.000000,500000.000000,60.000000,18.000000,49065.680000,5.000000,1.000000,100.000000,1.000000

In [9]:
df.isnull().sum()

Loan_ID             0
Customer_ID         0
Age                 0
Gender              0
City                0
Income              0
Employment_Type     0
Credit_Score        0
Loan_Amount         0
Loan_Term_Months    0
Interest_Rate       0
EMI                 0
Existing_Loans      0
Debt_to_Income      0
Payment_History     0
Loan_Purpose        0
Default_Flag        0
Application_Date    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95000 entries, 0 to 94999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Loan_ID           95000 non-null  object
 1   Customer_ID       95000 non-null  int64
 2   Age               95000 non-null  int64
 3   Gender            95000 non-null  object
 4   City              95000 non-null  object
 5   Income            95000 non-null  int64
 6   Employment_Type   95000 non-null  object
 7   Credit_Score      95000 non-null  int64
 8   Loan_Amount       95000 non-null  int64
 9   Loan_Term_Months  95000 non-null  int64
 10  Interest_Rate     95000 non-null  float64
 11  EMI               95000 non-null  float64
 12  Existing_Loans    95000 non-null  int64
 13  Debt_to_Income    95000 non-null  float64
 14  Payment_History   95000 non-null  int64
 15  Loan_Purpose      95000 non-null  object
 16  Default_Flag      95000 non-null  int64
 17  Application_Date  95000 non-null  object
dtypes: float64(3), int64(9), object(6)
memory usage: 13.0+ MB

In [11]:
df.drop_duplicates()

,Loan_ID,Customer_ID,Age,Gender,City,Income,Employment_Type,Credit_Score,Loan_Amount,Loan_Term_Months,Interest_Rate,EMI,Existing_Loans,Debt_to_Income,Payment_History,Loan_Purpose,Default_Flag,Application_Date
0,L0,573890,29,Male,Chennai,60745,Unemployed,722,324677,12,11.70,30222.02,5,1.00,18,Home,0,2017-09-06
1,L1,618322,22,Other,Bhopal,83424,Self-Employed,387,155281,36,15.96,5001.77,3,0.71,23,Education,1,2016-12-18
2,L2,734045,29,Other,Mumbai,113963,Unemployed,493,79923,36,17.37,2605.71,0,0.68,32,Car,0,2022-08-16
3,L3,302103,35,Male,Mumbai,53137,Unemployed,465,225259,60,7.61,4040.02,5,0.16,32,Car,0,2021-06-18
4,L4,91731,38,Male,Bhopal,38439,Salaried,789,407615,12,7.05,36362.65,4,0.32,1,Car,1,2021-04-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94995,L94995,556371,20,Other,Kolkata,134094,Self-Employed,860,102145,36,10.52,3135.85,2,0.39,45,Personal,1,2022-08-21
94996,L94996,966331,60,Female,Kolkata,167802,Self-Employed,676,430397,24,11.84,20056.50,5,0.42,94,Business,0,2016-06-30
94997,L94997,361133,57,Male,Mumbai,113700,Unemployed,653,467880,12,12.16,43731.18,0,0.85,99,Business,1,2018-05-24
94998,L94998,934984,22,Other,Bhopal,170375,Salaried,521,177517,24,14.65,8480.14,4,0.76,73,Personal,1,2019-04-05
94999,L94999,339337,34,Female,Mumbai,174125,Unemployed,616,389875,36,12.82,12218.25,5,0.46,21,Education,1,2015-05-03

Visualization Dashboard

In [12]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [13]:
# Load file
df = pd.read_csv("C:/Users/hp/OneDrive/Desktop/Project github/loan_default_risk_data.csv")

In [14]:
# Date format
df["Application_Date"] = pd.to_datetime(df["Application_Date"])

In [15]:
# -----------------------------
# KPI VALUES
# -----------------------------
total_loans = df["Loan_ID"].nunique()
total_amount = df["Loan_Amount"].sum()
avg_interest = df["Interest_Rate"].mean()
default_rate = df["Default_Flag"].mean() * 100
avg_credit = df["Credit_Score"].mean()

print("Total Loans:", total_loans)
print("Total Loan Amount:", total_amount)
print("Average Interest Rate:", round(avg_interest, 2))
print("Default Rate %:", round(default_rate, 2))
print("Average Credit Score:", round(avg_credit, 2))

Total Loans: 95000
Total Loan Amount: 23997171132
Average Interest Rate: 11.5
Default Rate %: 49.89
Average Credit Score: 599.23

In [16]:
# -----------------------------
# 1. Loan Applications Trend
# -----------------------------
trend = df.groupby(df["Application_Date"].dt.to_period("M")).size().reset_index(name="Applications")
trend["Application_Date"] = trend["Application_Date"].astype(str)

fig1 = px.line(
    trend,
    x="Application_Date",
    y="Applications",
    title="Loan Applications Over Time"
)
fig1.show()

In [17]:
# -----------------------------
# 2. Loan Amount by City
# -----------------------------
city_loan = df.groupby("City")["Loan_Amount"].sum().reset_index()

fig2 = px.bar(
    city_loan.sort_values("Loan_Amount", ascending=False).head(10),
    x="City",
    y="Loan_Amount",
    title="Top 10 Cities by Loan Amount"
)
fig2.show()

In [18]:
# -----------------------------
# 3. Loan Purpose Distribution
# -----------------------------
purpose = df["Loan_Purpose"].value_counts().reset_index()
purpose.columns = ["Loan_Purpose", "Count"]

fig3 = px.pie(
    purpose,
    names="Loan_Purpose",
    values="Count",
    title="Loan Purpose Distribution"
)
fig3.show()

In [19]:
# -----------------------------
# 4. Default Rate by Employment Type
# -----------------------------
default_emp = df.groupby("Employment_Type")["Default_Flag"].mean().reset_index()
default_emp["Default_Flag"] *= 100

fig4 = px.bar(
    default_emp,
    x="Employment_Type",
    y="Default_Flag",
    title="Default Rate by Employment Type"
)
fig4.show()

In [20]:
# -----------------------------
# 5. Credit Score vs Loan Amount
# -----------------------------
fig5 = px.scatter(
    df,
    x="Credit_Score",
    y="Loan_Amount",
    color="Default_Flag",
    title="Credit Score vs Loan Amount"
)
fig5.show()

In [21]:
# -----------------------------
# 6. Age Group Analysis
# -----------------------------
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[18, 25, 35, 45, 55, 65],
    labels=["18-25", "26-35", "36-45", "46-55", "56-65"]
)

age_loan = df.groupby("Age_Group")["Loan_Amount"].sum().reset_index()

fig6 = px.bar(
    age_loan,
    x="Age_Group",
    y="Loan_Amount",
    title="Loan Amount by Age Group"
)
fig6.show()

In [22]:
# -----------------------------
# 7. Income vs EMI
# -----------------------------
fig7 = px.scatter(
    df,
    x="Income",
    y="EMI",
    color="Default_Flag",
    title="Income vs EMI"
)
fig7.show()

In [23]:
# -----------------------------
# 8. Debt-to-Income by Default
# -----------------------------
fig8 = px.box(
    df,
    x="Default_Flag",
    y="Debt_to_Income",
    title="Debt-to-Income Ratio by Default"
)
fig8.show()

In [24]:
# -----------------------------
# 9. Payment History Distribution
# -----------------------------
fig9 = px.histogram(
    df,
    x="Payment_History",
    nbins=20,
    title="Payment History Distribution"
)
fig9.show()

In [25]:
# -----------------------------
# 10. Correlation Heatmap
# -----------------------------
num_cols = [
    "Age", "Income", "Credit_Score", "Loan_Amount",
    "Loan_Term_Months", "Interest_Rate", "EMI",
    "Existing_Loans", "Debt_to_Income", "Payment_History"
]

corr = df[num_cols].corr()

fig10 = px.imshow(
    corr,
    text_auto=True,
    title="Correlation Heatmap"
)
fig10.show()