Market Basket Analysis

In [2]:
import sys
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.1.1)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

Loading Dataset

In [3]:
df = pd.read_csv("/market_basket_analysis_data.csv")

Data Cleaning

In [4]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,Discount,Total_Amount,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,0.26,17656.41,UPI,17,0,23:03,1,1
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,0.05,17646.43,Cash,14,0,02:46,1,1
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,0.29,29932.17,UPI,16,1,00:46,1,1
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,0.27,22018.99,Cash,7,1,17:28,1,0
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,0.45,6282.98,Wallet,15,1,12:12,1,1

In [5]:
df.tail()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,Discount,Total_Amount,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag
49995,T49995,509321,2025-01-20,4480,East,Fashion,Product_A,Brand_Z,1,1068.22,0.08,982.76,UPI,20,1,03:15,0,1
49996,T49996,231132,2023-08-16,3461,East,Groceries,Product_C,Brand_X,8,541.57,0.43,2469.56,UPI,15,1,17:28,1,1
49997,T49997,339786,2023-02-11,5557,East,Electronics,Product_B,Brand_Z,1,1773.13,0.08,1631.28,Card,5,1,20:14,1,1
49998,T49998,707338,2023-07-10,6083,East,Electronics,Product_C,Brand_Z,1,3143.60,0.25,2357.70,Cash,3,1,14:10,1,0
49999,T49999,699927,2024-07-03,3103,West,Electronics,Product_C,Brand_X,10,4465.71,0.15,37958.53,Card,20,1,14:06,1,0

In [6]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Store_ID',
       'Region', 'Product_Category', 'Product_Name', 'Brand', 'Quantity',
       'Unit_Price', 'Discount', 'Total_Amount', 'Payment_Method',
       'Basket_Size', 'Loyalty_Customer', 'Purchase_Time', 'Promotion_Applied',
       'Weekend_Flag'],
      dtype='object')

In [7]:
df.shape

(50000, 18)

Exploratory Data Analysis

In [8]:
df.describe()

,Customer_ID,Store_ID,Quantity,Unit_Price,Discount,Total_Amount,Basket_Size,Loyalty_Customer,Promotion_Applied,Weekend_Flag
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,506096.375660,5033.662240,5.52538,2528.098656,0.249462,10481.747262,10.502320,0.498220,0.500060,0.498440
std,285319.499564,2853.407635,2.87077,1429.336518,0.144310,9004.509589,5.743345,0.500002,0.500005,0.500003
min,10012.000000,100.000000,1.00000,50.060000,0.000000,27.550000,1.000000,0.000000,0.000000,0.000000
25%,258689.500000,2570.000000,3.00000,1291.467500,0.120000,3263.125000,6.000000,0.000000,0.000000,0.000000
50%,507747.000000,5021.000000,6.00000,2519.965000,0.250000,7902.010000,10.000000,0.000000,1.000000,0.000000
75%,753705.500000,7484.000000,8.00000,3775.850000,0.370000,15459.567500,15.000000,1.000000,1.000000,1.000000
max,999974.000000,9999.000000,10.00000,4999.830000,0.500000,49366.940000,20.000000,1.000000,1.000000,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transaction_ID     50000 non-null  object
 1   Customer_ID        50000 non-null  int64
 2   Transaction_Date   50000 non-null  object
 3   Store_ID           50000 non-null  int64
 4   Region             50000 non-null  object
 5   Product_Category   50000 non-null  object
 6   Product_Name       50000 non-null  object
 7   Brand              50000 non-null  object
 8   Quantity           50000 non-null  int64
 9   Unit_Price         50000 non-null  float64
 10  Discount           50000 non-null  float64
 11  Total_Amount       50000 non-null  float64
 12  Payment_Method     50000 non-null  object
 13  Basket_Size        50000 non-null  int64
 14  Loyalty_Customer   50000 non-null  int64
 15  Purchase_Time      50000 non-null  object
 16  Promotion_Applied  50000 non-null  int64
 17  Weekend_Flag       50000 non-null  int64
dtypes: float64(3), int64(7), object(8)
memory usage: 6.9+ MB

In [10]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Transaction_Date     0
Store_ID             0
Region               0
Product_Category     0
Product_Name         0
Brand                0
Quantity             0
Unit_Price           0
Discount             0
Total_Amount         0
Payment_Method       0
Basket_Size          0
Loyalty_Customer     0
Purchase_Time        0
Promotion_Applied    0
Weekend_Flag         0
dtype: int64

In [11]:
df.drop_duplicates()

,Transaction_ID,Customer_ID,Transaction_Date,Store_ID,Region,Product_Category,Product_Name,Brand,Quantity,Unit_Price,Discount,Total_Amount,Payment_Method,Basket_Size,Loyalty_Customer,Purchase_Time,Promotion_Applied,Weekend_Flag
0,T0,771319,2022-11-15,2137,East,Groceries,Product_A,Brand_Z,6,3976.67,0.26,17656.41,UPI,17,0,23:03,1,1
1,T1,970179,2025-04-10,3357,South,Groceries,Product_C,Brand_X,9,2063.91,0.05,17646.43,Cash,14,0,02:46,1,1
2,T2,660192,2023-11-29,6249,East,Electronics,Product_C,Brand_X,9,4684.22,0.29,29932.17,UPI,16,1,00:46,1,1
3,T3,800878,2024-11-30,5427,North,Electronics,Product_C,Brand_Y,7,4309.00,0.27,22018.99,Cash,7,1,17:28,1,0
4,T4,239043,2024-11-09,3883,East,Fashion,Product_A,Brand_Z,5,2284.72,0.45,6282.98,Wallet,15,1,12:12,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,T49995,509321,2025-01-20,4480,East,Fashion,Product_A,Brand_Z,1,1068.22,0.08,982.76,UPI,20,1,03:15,0,1
49996,T49996,231132,2023-08-16,3461,East,Groceries,Product_C,Brand_X,8,541.57,0.43,2469.56,UPI,15,1,17:28,1,1
49997,T49997,339786,2023-02-11,5557,East,Electronics,Product_B,Brand_Z,1,1773.13,0.08,1631.28,Card,5,1,20:14,1,1
49998,T49998,707338,2023-07-10,6083,East,Electronics,Product_C,Brand_Z,1,3143.60,0.25,2357.70,Cash,3,1,14:10,1,0
49999,T49999,699927,2024-07-03,3103,West,Electronics,Product_C,Brand_X,10,4465.71,0.15,37958.53,Card,20,1,14:06,1,0

Visualization Dashboard

In [12]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [13]:
# Load dataset
df = pd.read_csv("/market_basket_analysis_data.csv")

In [14]:
# -----------------------------
# Basic preprocessing
# -----------------------------
df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

In [15]:
# Create useful time columns
df['Month'] = df['Transaction_Date'].dt.to_period('M').astype(str)
df['Day_Name'] = df['Transaction_Date'].dt.day_name()

In [16]:
# -----------------------------
# KPI values
# -----------------------------
total_sales = df['Total_Amount'].sum()
total_transactions = df['Transaction_ID'].nunique()
avg_basket = df['Basket_Size'].mean()
avg_discount = df['Discount'].mean()
loyalty_rate = df['Loyalty_Customer'].mean() * 100

print("Total Sales:", round(total_sales, 2))
print("Total Transactions:", total_transactions)
print("Average Basket Size:", round(avg_basket, 2))
print("Average Discount:", round(avg_discount, 2))
print("Loyalty Customer %:", round(loyalty_rate, 2))

Total Sales: 524087363.08
Total Transactions: 50000
Average Basket Size: 10.5
Average Discount: 0.25
Loyalty Customer %: 49.82

In [17]:
# ==========================================================
# 1. Sales Trend Over Time
# ==========================================================
sales_trend = df.groupby('Month')['Total_Amount'].sum().reset_index()

fig1 = px.line(
    sales_trend,
    x='Month',
    y='Total_Amount',
    title='Sales Trend Over Time'
)
fig1.show()

In [18]:
# ==========================================================
# 2. Sales by Region
# ==========================================================
region_sales = df.groupby('Region')['Total_Amount'].sum().reset_index()

fig2 = px.bar(
    region_sales,
    x='Region',
    y='Total_Amount',
    title='Sales by Region'
)
fig2.show()

In [26]:
# ==========================================================
# 3. Product Category Performance
# ==========================================================
category_sales = df.groupby('Product_Category')['Total_Amount'].sum().reset_index()

fig3 = px.bar(
    category_sales,
    x='Product_Category',
    y='Total_Amount',
    title='Sales by Product Category'
)
fig3.show()

In [24]:
# ==========================================================
# 4. Top 10 Products
# ==========================================================
top_products = (
    df.groupby('Product_Name')['Total_Amount']
    .sum()
    .nlargest(10)
    .reset_index()
)

fig4 = px.bar(
    top_products,
    x='Total_Amount',
    y='Product_Name',
    orientation='h',
    title='Top 10 Products'
)
fig4.show()

In [25]:
# ==========================================================
# 5. Payment Method Distribution
# ==========================================================
payment_sales = df.groupby('Payment_Method')['Total_Amount'].sum().reset_index()

fig5 = px.pie(
    payment_sales,
    names='Payment_Method',
    values='Total_Amount',
    title='Payment Method Distribution'
)
fig5.show()

In [27]:
# ==========================================================
# 6. Brand Performance
# ==========================================================
brand_sales = (
    df.groupby('Brand')['Total_Amount']
    .sum()
    .nlargest(10)
    .reset_index()
)

fig6 = px.bar(
    brand_sales,
    x='Brand',
    y='Total_Amount',
    title='Top 10 Brands'
)
fig6.show()

In [28]:
# ==========================================================
# 7. Weekend vs Weekday Sales
# ==========================================================
weekend_sales = df.groupby('Weekend_Flag')['Total_Amount'].sum().reset_index()

fig7 = px.bar(
    weekend_sales,
    x='Weekend_Flag',
    y='Total_Amount',
    title='Weekend vs Weekday Sales'
)
fig7.show()

In [29]:
# ==========================================================
# 8. Promotion Impact
# ==========================================================
promo_sales = df.groupby('Promotion_Applied')['Total_Amount'].mean().reset_index()

fig8 = px.bar(
    promo_sales,
    x='Promotion_Applied',
    y='Total_Amount',
    title='Average Sales: Promotion Impact'
)
fig8.show()

In [30]:
# ==========================================================
# 9. Purchase Time Analysis
# ==========================================================
time_sales = df.groupby('Purchase_Time')['Total_Amount'].sum().reset_index()

fig9 = px.bar(
    time_sales,
    x='Purchase_Time',
    y='Total_Amount',
    title='Sales by Purchase Time'
)
fig9.show()

In [31]:
# ==========================================================
# 10. Loyalty Customer Impact
# ==========================================================
loyalty_sales = df.groupby('Loyalty_Customer')['Total_Amount'].mean().reset_index()

fig10 = px.bar(
    loyalty_sales,
    x='Loyalty_Customer',
    y='Total_Amount',
    title='Average Spend: Loyalty vs Non-Loyalty'
)
fig10.show()